
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootPage1({ children }) {
  return (
    <div>
        <h1>Layout Page1</h1>
        {children}
    </div>
  )
}
